# Generated by Django 4.0 on 2022-03-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=64)),
                ('is_new', models.CharField(max_length=16)),
                ('dwelling_type', models.CharField(max_length=64)),
                ('tenure', models.CharField(max_length=32)),
                ('price_low', models.IntegerField()),
                ('price_high', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('page_type', models.CharField(max_length=16)),
            ],
        ),
    ]
