# Generated by Django 4.0.4 on 2022-04-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_remove_filter_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=8)),
                ('name_number', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=64)),
                ('is_new', models.CharField(max_length=16)),
                ('dwelling_type', models.CharField(max_length=64)),
                ('tenure', models.CharField(max_length=32)),
                ('price_low', models.IntegerField()),
                ('price_high', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('response_time', models.FloatField()),
                ('IP_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='name_number',
            field=models.CharField(default=-1, max_length=128),
            preserve_default=False,
        ),
    ]
