# Generated by Django 4.0.4 on 2022-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_usagestats_filter_name_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='postcode',
            field=models.CharField(max_length=7),
        ),
    ]
