# Generated by Django 4.0.4 on 2022-04-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_filter_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='name_number',
            new_name='paon',
        ),
        migrations.RenameField(
            model_name='usagestats',
            old_name='name_number',
            new_name='paon',
        ),
    ]
