# Generated by Django 4.0.4 on 2022-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_rename_name_number_filter_paon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagestats',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='county',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='dwelling_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='is_new',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='paon',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='postcode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='price_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='price_low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='street',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='tenure',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
