# Generated by Django 4.0.4 on 2022-04-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_usagestats_city_alter_usagestats_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='usagestats',
            name='is_new',
        ),
    ]
