# Generated by Django 4.0.4 on 2022-04-23 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_filter_is_new_remove_usagestats_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagestats',
            name='time_of_submission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
